spring:
  application:
    name: demo
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/demo}
    username: ${SPRING_DATASOURCE_USERNAME:demo}
    password: ${SPRING_DATASOURCE_PASSWORD:demo}
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false


app:
  jwt:
    secret: "my-super-juper-dlinniy-secret-slovo-ha-ha-ha-ha-ha-ha"
    expiration-access: 36000
    expiration-refresh: 86400
